### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by 2sn** [ADACS-Australia/starfit-server#13]
1) How can I use a branch for testing deployment, e.g., on `starfit.xyz`?

2) How can I make a deploy version use a specific branch of `starfit`, e.g., from PyPI or from Test PyPI?

**Comment by 2sn** [comment]
[1] I see, for the deployment playbook, I can just check out the branch I want, and instal from there.

That leaves just [2].  I see somewhere in the configuration `latest` but can I specify something else on the command line?

**Comment by 2sn** [comment]
`starfit-server/roles/starfit/tasks/main.yml`:
```
- name: Install StarFit
  pip:
    name: starfit
    state: latest
```
